cmd/constants/constants.go
cmd/project/get_project.go
cmd/root.go

This commit adds the project get command for the
user to get the project by name or ID.
This PR depends on: #1.

Add `project get` command

---

.github/dependabot.yml
.github/workflows/publish_release.yml
.goreleaser.yaml
go.mod

This PR fixes the [failing workflow](https://github.com/goharbor/harbor-cli/actions/runs/7905056008)
This PR suggests tagging `v0.1.0-beta.1` and proceeding with the release.
Updated goreleaser configuration, @Vad1mo . Add **GH_TOKEN** secret with `repo scope, write:packages`.
Also I included a dependabot, to automate dependency updates.
After merging, let's release the packages on Homebrew, Winget, Nix, and Snap.

bump: fix the goreleaser release cycle & Dependabot

---

cmd/harbor/root/project/create.go
pkg/views/project/create/view.go
pkg/views/project/list/view.go

Refine the project creation schema and update the project table to incorporate the 'Type' field.
We have integrated the proxy cache into this project schema.

feat: fix the create schema of project, update the project table to take Type into action

---

cmd/harbor/root/login.go

Previously the flags provided with the command were not used by the command. 
Fixed it. The variables that were storing the values of the flag were not used for login.

Fixed the `login` command with flags input

---

cmd/harbor/root/login.go
go.mod
test/e2e/login_test.go

Fixes: #23 
This PR requires PR #89 to be merged as that solves the feature.
The test data are written directly on the code. However, we need to decide how the test data will be managed and where should be stored. Looking for guidelines @Vad1mo @amands98.
These tests do not mock as the motive of e2e is to test if the whole procedure is working fine. Only external modules can be mocked if necessary. Mocking the internal modules would not let to check the integration of all the modules.
I had to change the `Run` function to `RunE` function, because otherwise the assertions could not be tested. The problem is with the `fmt.Println()` function, as it will not write to the buffer provided in the test function.
I have checked many places and investigated. Their method works because those …

Added e2e for the `login` command using flags.

---

pkg/views/project/list/view.go
pkg/views/user/list/view.go

The `project list` and `user list` table has a missing ID column, it will be easier for the user to see the table, identify the IDs.
Adding this column will enhance the user experience and be beneficial for the project.

feat: add ID to `list` table.

---

cmd/harbor/root/project/create.go

- Allow project name to be specified as a positional argument in the `project create` command.
- Change the default value of the `--public` flag to `false`, making projects private by default.
- Remove the `--name` flag and update the command to handle the project name from the positional argument.
- Create a private project by default:
`./harbor project create bupd-test` will work
- Create a public project:
`./harbor create project bupd-test --public` 
These changes improve user experience by simplifying command usage and enhance security by setting a private default for projects.

feat: Fix Creating Project Flow

---

cmd/harbor/root/registry/create.go
cmd/harbor/root/registry/update.go
pkg/api/registry_handler.go
pkg/api/types.go
pkg/utils/helper.go
pkg/utils/utils.go
pkg/views/registry/create/view.go
pkg/views/registry/list/view.go
pkg/views/registry/select/view.go

This PR improves the user experience of the registry create command by fetching and presenting default registries available. This enhancement guides users to select the correct registry provider, reducing the likelihood of errors and streamlining the setup process.
Previously, users had to manually enter registry provider details, which often led to errors and a frustrating experience. Incorrect registry configurations could result in errors that were difficult to diagnose and fix.
To address this issue, I have implemented a feature that fetches a list of registry providers in harbor and presents them to the user during the registry create process. This allows users to select a registry from a predefined list, ensuring correct configuration and reducing errors.
- Added functionality to …

Enhance `registry create` Command

---

cmd/harbor/root/user/elevate.go
pkg/views/confirmation.go

@amands98 ,
Completed the TODO in the elevate command.
Created confirmation for elevating user to admin.

feat: Created confirmation for elevating user to admin

---

cmd/harbor/root/cmd.go
cmd/harbor/root/health.go
pkg/api/health_handler.go
pkg/views/health/view.go
pkg/views/styles.go

This pr provides a status check of various system components, allowing administrators to quickly assess the overall health and operational status of the Harbor registry system.
Command:
`harbor health` : Get the health status of Harbor components

feat: add cli for health status

---

dagger/main.go

Bump golangci-lint to latest release

Bump golangci-lint to latest

---

.github/workflows/docker_publish.yml

Per #197 :
> Docker Publish Workflow: Update the [docker_publish_workflow](https://github.com/goharbor/harbor-cli/blob/main/.github/workflows/docker_publish.yml) to trigger only on tag creation or release events, preventing runs on PRs.
Updates the `docker-publish` workflow to only run for release and tag events.

Trigger docker-publish workflow only on release or tag events

---

.github/workflows/docker_publish.yml
.github/workflows/publish_release.yml
.github/workflows/pull-request.yml

Updates core GHA dependencies (`checkout`,`setup-go`) to latest stable versions

bumps core GHA dependencies

---

.github/workflows/docker_publish.yml
.github/workflows/publish_release.yml
.github/workflows/pull-request.yml
dagger/main.go

Per #197:
> Remove Module Dependency: Eliminate the dependency on the module, as seen in [this section](https://github.com/goharbor/harbor-cli/blob/62c3945a773d405a4cc8bfa9bad11031b69c54dc/.github/workflows/pull-request.yml#L42C10-L42C58). It's an unnecessary overhead.
> Dagger Flag Update: Replace --directory-arg with the --source flag in the workflow, and set it as the default using the latest Dagger version.
- Drops the usage of a remote `dagger` module and instead looks to use the one local to the repository
- Updates dagger function(s) to use common `source` parameter

use local dagger module in pull-request workflow

---

.golangci.yaml
cmd/harbor/root/health.go
pkg/api/health_handler.go
pkg/views/health/view.go

Per #197:
> Add Formatting Check on Lint Workflow: To maintain consistent formatting.
This adds an initial `.golangci.yaml` config file and adds in the `gofmt` linter to check basic formatting. There are all kinds of other linters/formatter checks to add here, but didn't want to get too opinionated from the start.

add initial .golangci.yaml config with formatter

---

.github/workflows/pull-request.yml

Per #197 :
> Add Build Check Workflow: To check if building binaries for multiple operating systems and architectures are working as expected.
This adds the existing `build` dagger function to the `pull-request` workflow to ensure that binaries for multiple OS and arch combinations can be done successfully.

adds build function to pull-request workflow

---

.github/workflows/docker_publish.yml
.github/workflows/publish_release.yml
.github/workflows/pull-request.yml

This bumps the dagger-for-github action to the latest stable (which aligns with the dagger version in `dagger.json`)

bump dagger github action to latest

---

.github/workflows/pull-request.yml
dagger/main.go

Updates the last dagger function `pull-request` to use `source`

update pull-request function to use source

---

.github/workflows/docker_publish.yml
.github/workflows/publish_release.yml
README.md
dagger.json
dagger/main.go

Hello! 
I went through the existing Dagger module and refactored things a bit to encourage best practices around types, documentation, constructors, etc. 
Here's an overview of the changes. 
1. Refactor GHA workflow to use secrets from env instead of strings 
2. Refactor GHA workflow to not set up go since it is never used directly 
3. Use constructor pattern to clean up functions 
4. More consistently apply code style 
5. Use secrets instead of strings for secrets because this prevents them from ever leaking in logs or cache 
6. Temporarily make build function private due to this bug: https://github.com/dagger/dagger/issues/8202#issuecomment-2317291483 
7. Have the new Build Dev function return a file instead of directory since its redundant.

Dagger Code Review

---

pkg/utils/helper.go

The username validator previously implemented only allowed alphanumeric characters, which resulted in rejecting valid usernames accepted by the server, such as `harbor-cli`. This inconsistency also caused failures in login tests.
To resolve this, the current implementation of the validator has been aligned with the server's username validation criteria. You can view the server-side validator [here](https://github.com/goharbor/harbor/blob/9e55afbb9a124dbe47562d56769ad4e9f14cb5ed/src/server/v2.0/handler/user.go#L514-L518).
This PR references issue #234

fixed username validator

---

.github/actions/publish-and-sign/action.yaml
.github/workflows/default.yaml
dagger/main.go

Print out the test results on screeen instead of the directory.

 print test output to screen

---

cmd/harbor/root/project/list.go
pkg/api/project_handler.go
pkg/prompt/prompt.go
pkg/views/project/list/view.go

Shows both private and public projects for project list cmd and allows the user to filter where the project list should be public/private
[Screencast from 17-11-24 03:05:51 PM IST.webm](https://github.com/user-attachments/assets/5a2cdb3a-bfdd-4e27-aaf3-bce9c2c2b536)
Solved another issue,

Shows both private and public projects for project list cmd

---

.github/workflows/default.yaml

fixed #278 
I recently updated the workflow trigger conditions for `push-latest-images` and `publish-release`.

bug: fix push-latest-images and publish-release

---

cmd/harbor/root/health.go
pkg/api/ping_handler.go

fix #211 
part of #94 
~~move the ping command handler and verify the API server first, before checking the status of the Harbor components.~~
Edit:
Add a Ping step to the health command that pings the server before checking its health status. Removing the need for separate ping command.

chore: move the ping to health handler

---

README.md

there was this issue that there was no command to move to cloned directory after cloning so this PR fixes that 
Earlier it gave error like this 
```
rizul@rizu:~$ go build -o harbor-cli cmd/harbor/main.go
package cmd/harbor/main.go is not in std (/snap/go/10748/src/cmd/harbor/main.go)
```

docs: update README to include directory change after cloning

---

cmd/harbor/root/project/logs.go
cmd/harbor/root/project/view.go
cmd/harbor/root/registry/view.go
cmd/harbor/root/repository/list.go
cmd/harbor/root/user/list.go

Fixes: #76 
Added missing parameters in the 
(1) go client `list` function of the `repo` and `user` commands 
(2) go client `getLogs` function of the `logs.go` file in the `project` command using options.
Added the `XIsResourceName` parameter for the `GetProjectParams` function. This parameter specifies whether the input is name or ID. 
Refactored the `view.go` file of the `project` command. 
Refactored the `view.go` file of the `registry` command: accessing the `credentialName`.

Added the missing options in some commands and refactored some commands.

---

cmd/harbor/root/project/delete.go
cmd/harbor/root/registry/delete.go
cmd/harbor/root/user/delete.go

This PR enhances the performance of the `harbor project delete` command by introducing concurrency to handle multiple project deletions in parallel. The changes ensure that the command is more efficient, especially when dealing with multiple projects.
- Concurrency Implementation:
- Added goroutines to execute `runDeleteProject` concurrently for each project specified in the command arguments.
- Implemented an error channel (errChan) to collect errors from each goroutine.
- Ensured all errors are logged appropriately after all goroutines have completed.
- Performance: By running deletions concurrently, the command execution time is significantly reduced when dealing with multiple projects.
- Reliability: Enhanced error handling ensures that all errors are captured and logged, providing …

feat: Improve Performance of ` delete` Command with Concurrency

---

doc/doc.go

This PR fixes the issue #362 where existing command documentation was not being updated when command details were modified. The documentation generator previously skipped generating markdown files if the file already existed, causing the documentation to become outdated.
- Removed the file existence check `(os.Stat)` in `MarkdownTreeCustom` to ensure that markdown files are regenerated even if they already exist.
-  Now, the markdown files are created or overwritten each time documentation generation is triggered, ensuring they reflect the latest command details.
- Removed the `os.Stat` check that prevented existing markdown files from being updated.
- Markdown files are now created or updated every time the documentation is generated.

fix: generate new docs for change in existing commands

---

cmd/harbor/root/labels/list.go
cmd/harbor/root/project/list.go
cmd/harbor/root/registry/list.go
cmd/harbor/root/repository/list.go
cmd/harbor/root/user/list.go

This PR updates the `user list` command in the Harbor CLI to support listing **all users** when no `--page-size` is specified (i.e., set to `0`). It mirrors the behavior of the `project list` command.
- Added support for repeated paginated API calls when `--page-size` is `0`, with a default of `page-size=100`.
- Ensures consistent behavior with other commands like `project list`.
- Introduced a check in relevant list views to **avoid printing empty tables**.
- If no entries are found, a clean message like `"No users found`` is printed instead. This is done for all list commands.
| CLI Input                         | Result                            |
|----------------------------------|-----------------------------------|
| `harbor user list`               | Fetches **all users** …

feat: Enhance `user list` cmd to fetch all users by default via paginated API calls

---

pkg/utils/encryption.go
test/e2e/encryption_test.go

**Fixes** #384
In containerized environments (e.g. harbor-cli containers), system keyring providers are often unavailable, making it impossible to securely store encryption keys.
Implement a `FileKeyring` type that serves as a fallback mechanism when no system keyring is detected. The encryption private key is now stored in an encrypted file within the user's home directory (`~/.harbor/keyring` by default).
- **Automatic Fallback**: System keyring remains first priority, FileKeyring used as secondary option
- **Secure Storage**:
- Strict `600` file permissions
- **Container-Friendly**: Works without DBus/Keychain access
- **New `init` Function**: Centralized provider selection logic
- Open to security hardening suggestions
1. Validated in Docker container (Golang:1.22)
2. Manual …

Add FileKeyring as fallback for secure key storage

---

pkg/views/artifact/list/view.go
pkg/views/artifact/tags/list/view.go
pkg/views/artifact/view/view.go
pkg/views/base/tablelist/model.go
pkg/views/health/view.go
pkg/views/label/list/view.go
pkg/views/project/list/view.go
pkg/views/project/logs/view.go
pkg/views/project/view/view.go
pkg/views/registry/list/view.go
pkg/views/registry/view/view.go
pkg/views/repository/list/view.go
pkg/views/repository/search/view.go
pkg/views/repository/view/view.go
pkg/views/schedule/list/view.go
pkg/views/user/list/view.go

- Introduced support for different table column configurations based on size (`xs`, `s`, `m`, `l`, `xl`).
- Defined `sizeMap` to map size labels to specific column configurations using predefined widths: `WidthXS`, `WidthS`, `WidthM`, `WidthL`, and `WidthXL`.
- Ensured each size layout maintains readability and avoids text truncation where possible.

feat: replace random widths with standard custom widths

---

pkg/utils/client.go

This PR addresses the issue of duplicated error messages during client initialization in the Harbor CLI. Previously, the same error was logged internally (using `log.Errorf`) and then also returned to the CLI command, resulting in multiple redundant outputs like:
```
ERRO failed to initialize client: ...
Error: failed to get projects list: ...
```
- Removed internal logging (`log.Errorf`) from `GetClient()` to prevent duplicate logs.
- Error is now propagated cleanly to the CLI layer, which can handle logging uniformly in one place.
- Improved clarity and user experience by showing each error **only once**, in a consistent format.
Now when a command like `harbor-cli project list` fails, the output is clean and free from duplication:
```
Error: failed to get projects list: failed to …
```

fix: remove repeated error logging in `project list` cmd

---

.goreleaser.yaml

For the moment the version of the CLI displayed in "harbor version" is wrong:
```
$ harbor version
Version:      0.1.0
Go version:
Git commit:   651cfb4090e8b0d396c1faa902e404c7bdc5e66a
Built:
OS/Arch:      darwin/arm64
```
This PR fix #400

Fix: Version in "harbor version" command

---

pkg/utils/helper.go

https://github.com/goharbor/harbor-cli/issues/297
Adds feature to login using URLs with leading slash. The inbuilt harbor modules don't seem to work the same if the URL has a leading slash. A simple workaround is to remove any trailing slashes from the URL before any further processing

Adds login with trailing slash

---

cmd/harbor/root/project/create.go

I think it is better to display a clear error message when an user don't specify registry-id for a proxy cache project creation.
Fix #394 
Tested with the PR:
```
$ ./harbor-cli project create docker-hub --proxy-cache
ERRO Use the --registry-id flag with a registry ID
```

Improve user message in proxy cache project creation without adding registry-id

---

README.md

https://github.com/goharbor/harbor-cli/issues/415
The location of the config has been incorrrectly set as `$HOME/.harbor/config.yaml` while it should be `$HOME/.config/harbor-cli/config.yaml`. Sets a default HARBOR_CLI_CONFIG in .zshrc and use it to alias harbor. This way we can keep track of updating locations of config file.

Updates incorrect config mount location and adds default value for HARBOR_CLI_CONFIG in README.md

---

pkg/utils/config.go

fixed #264 
a clear error message is logged :

fix: return proper error when a directory exists instead of config file

---

cmd/harbor/root/health.go
pkg/views/health/view.go
pkg/views/styles.go

This PR fixes a display alignment issue in the `health` command output of `harbor-cli`.
Previously, using `lipgloss` styles (e.g., `views.GreenStyle` and `views.RedStyle`) for coloring status values in the health report led to **misaligned columns** in the TUI table rendered by `bubbles/table`. This happened because `lipgloss.Render()` adds ANSI color codes, which aren't accounted for during table width calculations.
Replaced `lipgloss` styles with **raw ANSI escape codes** (`\033[32m` for green and `\033[31m` for red), ensuring consistent alignment and correct color rendering **without affecting column layout**.
(Status text now appears green or red based on health and is properly aligned.)
Raw ANSI sequences preserve correct width handling by avoiding extra padding or styling behavior …

Fix: Preserve Table Alignment While Adding Status Colors

---

.dagger/README.md

Fixes #194
Currently we lack how to use dagger in harbor-cli. and adding this will be helpful for beginners to understand on how to interact with dagger. to lint, build and publish images for harbor-cli via dagger.
Thanks.

Add Documentation for usage of dagger

---

pkg/api/info_handler.go

Fix: #461 
PreviouslyLoggedIn now displays context name instead of server address

fix: PreviouslyLoggedIn should display context name

---

cmd/harbor/root/cmd.go

Fixes: #464
Before: 
```
Official Harbor CLI
Usage:
harbor [command]
Examples:
// Base command:
harbor
// Display help about the command:
harbor help
Available Commands:
artifact      Manage artifacts
completion    Generate the autocompletion script for the specified shell
config        Manage the config of the Harbor CLI
cve-allowlist Manage system CVE allowlist
health        Get the health status of Harbor components
help          Help about any command
info          Display detailed Harbor system, statistics, and CLI environment information
instance      Manage preheat provider instances in Harbor
label         Manage labels in Harbor
login         Log in to Harbor registry
project       Manage projects and assign resources to them
quota         Manage quotas
registry      Manage …
```

Add groups to root help command

---

pkg/views/context/list/view.go

Fixes: #480 
---
these changes make it so that when the context is changed instead of the context coming to the top, the pointer simply moves to the selected context
---
Before:
After:

feat: fixing the pointer positioning with change in context

---

cmd/harbor/root/artifact/tags.go
pkg/views/repository/select/view.go

Fixes #435 
Currently, the Harbor CLI's interactive selection prompts don't properly support navigation between different selection levels. When a user presses 'q':
- The UI exits, but the command doesn't properly handle this special value
- Users can't easily go back to previous selection screens
- The selection process can get stuck in loops or require restarting the command
This PR implements proper handling of the 'q' key in interactive prompts to enable intuitive navigation:
- At the top-level prompt (project selection), 'q' exits the command
- At lower-level prompts (repository, artifact selection), 'q' goes back to the previous selection level
- Clear feedback messages inform users about navigation options

WIP: Add support for navigating interactive prompts with 'q' key

---

cmd/harbor/root/cmd.go
cmd/harbor/root/logs.go
cmd/harbor/root/project/robot/update.go
doc/cli-docs/harbor-logs.md
doc/cli-docs/harbor.md
doc/man-docs/man1/harbor-logs.1
doc/man-docs/man1/harbor.1
go.mod
go.sum
pkg/api/auditLogs_handler.go
pkg/api/robot_handler.go
pkg/views/logs/view.go
pkg/views/robot/update/view.go

This PR adds a new `harbor-cli logs` command that allows users to view and follow Harbor audit logs in real-time.
- **View audit logs**: Display recent audit logs for projects the user is a member of
- **Follow mode**: Real-time log tailing with `-f/--follow` flag (similar to `tail -f`)
- **Configurable refresh interval**: Set custom polling intervals with `--refresh-interval`
- **Pagination support**: Standard pagination with `--page` and `--page-size` flags
- **Query filtering**: Filter logs using `--query` parameter
- **Sorting**: Sort logs with `--sort` parameter
- **JSON output**: Support for JSON format output with `--output-format json`
```bash
harbor-cli logs
harbor-cli logs -f
harbor-cli logs -f --refresh-interval 2s
harbor-cli logs --query "operation=push"
harbor-cli logs …
```

feat(logs): add audit logs command with follow support

---

README.md

This pull request fixes a minor typo in readme.md
- **Before:** I you intend to run the CLI as a container...
- **After:** If you intend to run the CLI as a container...

Fix Typo in Readme.md

---

cmd/harbor/root/replication/cmd.go
cmd/harbor/root/replication/executions.go
cmd/harbor/root/replication/executions/list.go
cmd/harbor/root/replication/executions/view.go
cmd/harbor/root/replication/logs.go
doc/cli-docs/harbor-replication-executions-list.md
doc/cli-docs/harbor-replication-executions-view.md
doc/cli-docs/harbor-replication-executions.md
doc/cli-docs/harbor-replication-log.md
doc/cli-docs/harbor-replication.md
doc/man-docs/man1/harbor-replication-executions-list.1
doc/man-docs/man1/harbor-replication-executions-view.1
doc/man-docs/man1/harbor-replication-executions.1
doc/man-docs/man1/harbor-replication-log.1
go.mod
go.sum
pkg/api/replication_handler.go
pkg/prompt/prompt.go
pkg/views/replication/execution/list/view.go
pkg/views/replication/execution/view/view.go
pkg/views/replication/task/list/view.go
pkg/views/replication/task/select/view.go

Fixes #102
Fixes #497
This PR adds comprehensive **replication execution management** to **harbor-cli**, introducing commands to list, view, and retrieve logs for replication executions and their associated tasks.
* **`harbor replication executions list [POLICY_ID]`** - Lists all replication executions for a policy
* Interactive policy selection when no ID is provided
* Supports standard pagination, filtering, and sorting options
* JSON output format support for programmatic use
* **`harbor replication executions view [EXECUTION_ID]`** - Shows detailed execution information
* Property-value table format for single execution display
* Automatically displays associated tasks unless `--no-tasks` flag is used
* Interactive execution selection when no ID is provided
* **`harbor replication log …

Replication executions

---

cmd/harbor/root/cmd.go
cmd/harbor/root/password.go
cmd/harbor/root/user/cmd.go
cmd/harbor/root/user/password.go
doc/cli-docs/harbor-password.md
doc/cli-docs/harbor-user-password.md
doc/cli-docs/harbor-user.md
doc/cli-docs/harbor.md
doc/man-docs/man1/harbor-password.1
doc/man-docs/man1/harbor-user-password.1
doc/man-docs/man1/harbor.1
pkg/api/user_handler.go
pkg/views/password/change/view.go
pkg/views/password/reset/view.go

closes #523 
logs for user password update and own password

feat:add feature to change password for profile as well as user
