- README.md
- Added this README.md for initial start
- Proposed the harbor cli logo to make it more attractive
- Needs a lot of improvements with further progress ...
//cc @Vad1mo @amands98
PTAL!
> enhancement: Improve README.md

- cmd/harbor/root/project/create.go
- pkg/views/project/list/view.go
Fixes #117 and #118 
When user enter `harbor project create my_project` then it create a new private project my_project with unlimited quota.
And changed the project as private unless they are specified explicitly as public.
> Enhanced the create project flow

- cmd/harbor/root/artifact/scan.go
- cmd/harbor/root/artifact/tags.go
- cmd/harbor/root/registry/view.go
- pkg/views/registry/create/view.go
This PR is crucial for fixing the lint errors in the CLI.
This PR needs to be merged for the release.
> Fix Lint Errors

- cmd/harbor/root/project/create.go
This fixes #171 
More interactive way to create project
> feat: enhanced create project cmd

- .github/workflows/docker_publish.yml
- .gitignore
- dagger.gen.go
- dagger.json
- internal/dagger/dagger.gen.go
- main.go
> feat: Implemented docker publish function using dagger

- cmd/harbor/root/artifact/list.go
- pkg/utils/helper.go
- pkg/views/artifact/list/view.go
- create a new list view
- add util function for handling size
Closes #161 
New output
> feat: add table view to artifact list

- README.md
- dagger.json
- dagger/main.go
Allow to build the binary locally.
Replaces #215 #169
> add local build to dagger.

- pkg/utils/helper.go
Reverts goharbor/harbor-cli#239
pipeline fails
> Revert "fixed username validator"

- pkg/utils/helper.go
> fix: username validation

- .github/workflows/default.yaml
Fixes Release Workflow. which was previously failing on checkout repo.
- https://github.com/goharbor/harbor-cli/actions/runs/13412775443
cc // @Vad1mo
> fix: Release Workflow

- README.md
docs: reposition the FOSSA badge
> docs: reposition the FOSSA badge

- .dagger/main.go
> feat: add metadata labels and creation timestamp for image on artifacthub.io

- README.md
> Added more info how to use harbor-cli containers correctly

- README.md
- cmd/harbor/root/config/cmd.go
This PR corrects the config cmd description
Fixes: #425
> refactor: Config cmd description

- .dagger/main.go
- .github/workflows/default.yaml
https://github.com/goharbor/harbor-cli/issues/325
Adds a vulnerability check workflow in `.dagger/main.go` to check for known vulnerabilities using `govulncheck`
> Adds Vulnerability Check workflow

- .dagger/main.go
- .github/workflows/default.yaml
- dagger.json
- go.mod
- Fix goreleaser issue
- Add Test Release pipeline
> Fix goreleaser

- pkg/views/info/list/view.go
> fix: Show Banner messsage in system info instead of json

- cmd/harbor/root/login.go
- cmd/harbor/root/login_test.go
- doc/cli-docs/harbor-login.md
- doc/man-docs/man1/harbor-login.1
https://github.com/goharbor/harbor-cli/issues/476
Removes the context switching via login command.
> removes context switch via login command

- cmd/harbor/root/context/switch.go
- pkg/prompt/prompt.go
- pkg/views/context/list/view.go
- pkg/views/context/switch/view.go
Makes changes suggested in: https://github.com/goharbor/harbor-cli/pull/445
> adds changes suggested in context command

- cmd/harbor/root/project/robot/list.go
- examples/config/robot-account/README.md
- pkg/views/base/tablegrid/model.go
- pkg/views/robot/create/view.go
This pull request implements the requested changes from the review of **PR #489** and adds several usability enhancements.
---
* **Improved control clarity** – toggles replaced with explicit on/off actions
* `Ctrl + J` — Turn **ON** all cells in the current **row**
* `Ctrl + K` — Turn **OFF** all cells in the current **row**
* `Ctrl + H` — Turn **ON** all cells in the current **column**
* `Ctrl + L` — Turn **OFF** all cells in the current **column**
* **Table‑wide controls**
* `Ctrl + A` — Turn **ON** every cell in the table
* `Ctrl + D` — Turn **OFF** every cell in the table
* **Updated documentation** – footer text now clearly shows the purpose of each shortcut
* **Better validation**
* Rejects non‑integer inputs
* Disallows `0` or negative values (except `‑1`)
* Provides clearer, more …
> Improve table grid controls and form validation (Follow‑up Improvements to PR #489)

- README.md
This PR adds Go Report Card to the Readme.
> feat: add go report card

- cmd/harbor/root/logs.go
- doc/cli-docs/harbor-logs.md
- doc/man-docs/man1/harbor-logs.1
@Vad1mo As discussed today in the community meeting. Seems it was 1 second instead of 100 ms, but it is maybe still to short.
> Increased the logs follow refresh interval to 5s as a default

- cmd/harbor/root/login.go
- doc/cli-docs/harbor-login.md
- doc/man-docs/man1/harbor-login.1
- go.mod
- go.sum
- Fixes #508
- Added `--context-name` flag.
- Added a conditional check to auto-fill loginView.Name.
> Fix: login `--name` flag to `context-name`

- CONTRIBUTING.md
Go language version in Contribution.md changed from >=1.20 to >=1.24.
> Doc change
